FROM maven:3-jdk-11-slim@sha256:2cb7c73ba2fd0f7ae64cfabd99180030ec85841a1197b4ae821d21836cb0aa3b as buildtime

WORKDIR /build
COPY . .

RUN mvn clean package

FROM amazoncorretto:11@sha256:7e1c9ca2ceb084b6dd916cadcceaa82f0ceeae275474a92fe0e9b5a531356098 as runtime

WORKDIR /app

COPY --from=buildtime /build/target/*.jar /app/library.jar